version: '2.0'
services:
  app:
    image: onlineshop-zotteltec
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres