version: '2.0'
services:
  app:
    image: tomee
    ports:
      - "8080:8080"
    volumes:
      - /Users/gregor.vonfluee/development/IdeaProjects/Zotteltec/ear/build/libs:/usr/local/tomee/webapps
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
